### ISSUE TITLE
[SDSC] Evaluate Open-Metadata

### ISSUE THREAD

**Issue by sabrinaossey** [SDSC-ORD/ORD_landscaping#1]
Acceptance criteria:
- [x] Create new Settings with Teams, Groups, and Policies.
- [x] Connect to a Database service.
- [ ] Deploy an airflow Pipeline.

The evaluation report is available here: https://sdsc.atlassian.net/wiki/spaces/ORDES/pages/2508980301/OpenMetadata

**Comment by cmdoret** [comment]
@rmfranken
